### ISSUE TITLE
HomeBridge 1.3.0

### ISSUE THREAD

**Issue by bosco90** [donavanbecker/homebridge-meross#204]
Hi,
Just wanted to let you know how the plugin works with Homebridge 1.3.0 Beta.

**Describe The Bug:**

In the Home app everything works fine, just a new log appears at every device status change (On > Off, Off > On)

**To Reproduce:**

Install Homebridge 1.3.0 Beta

**Expected behavior:**

N/D

**Logs:**

[17/2/2021, 09:20:17] [Presa] MSS425E turned Off
[17/2/2021, 09:20:17] Received warning for the plugin 'homebridge-meross' from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response!

**Homebridge Config:**

        {
            "model": "MSS425E",
            "name": "Presa",
            "firmwareRevision": "2.1.3",
            "deviceUrl": "192.168.xx.xx",
            "channel": 1,
            "messageId": "xxxx",
            "timestamp": xxxx,
            "sign": "xxxx",
            "accessory": "Meross"
        },

# **Environment:**

- **Node.js Version**: v14.15.5
- **NPM Version**: v6.14.11
- **Homebridge Version**: v1.3.0-beta.58
- **Homebridge Meross Plugin Version**: v3.5.0
- **Homebridge Config UI X Plugin Version**: v4.39.0
- **Operating System**:  Ubuntu

**Comment by SemoTech** [comment]
Same issue continues after the release of Homebridge 1.3.0, indicating this issue is with the plugin.

LOGS: `Received warning for the plugin 'homebridge-meross' from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response!`

ENVIRONMENT:

Node.js version: v14.15.5
Npm version: v7.5.4
Homebridge version: v1.3.0 (release)
Homebridge Meross Plugin version: v3.5.0
Homebridge Config UI X Plugin version: v4.39.0
Operating System: Raspbian GNU/Linux Buster (10)
Hardware:  Raspberry Pi 4B w/ 2GB

**Comment by donavanbecker** [comment]
Yes this is something with homebridge v1.3.0 that it is displaying. If someone wants to do a PR to fix this I will accept it. If not. I will work on correcting it when I have my other 2 main plugins working good with homebridge v1.3.0

**Comment by SemoTech** [comment]
Just an FYI that the issues still persist even with latest Homebridge v1.3.1

**Comment by donavanbecker** [comment]
Pull Request are welcome!

**Comment by donavanbecker** [comment]
Checkout #228

**Comment by donavanbecker** [comment]
#228/#227 takes care of this.
