### ISSUE TITLE
Disable native HomeKit accessories

### ISSUE THREAD

**Issue by ShaunRoberts543** [donavanbecker/homebridge-meross#327]
Hello, I have a handful of HomeKit native Meross accessories.  I use the cloud option and it doubles up everything that is HomeKit native.  Is there a way to do that differently and exclude HomeKit native devices?

Thank you.

**Comment by bwp91** [comment]
Hi @ShaunRoberts543 

There is no option to 'globally' ignore homekit native devices. In fact I don't think the plugin can even tell if a specific device is the homekit native version or not.

You can add an entry in the config per device (using serial number) and use the 'Ignore From HomeKit' option. I appreciate this is a bit of a setup if you have a lot of devices you wish to ignore, but it only needs to be done once.

**Comment by ShaunRoberts543** [comment]
Thank you.  It is not a bother to add the devices individually, I am glad I can do that now.  Just wanted to throw the conversation out there.  I remember a plug in that offered a selection to disable HomeKit accessories as a selection, but I cannot remember what it was.  Hue maybe?

Appreciate the reply!

**Comment by bwp91** [comment]
It may be hue, not sure.
If there were a way for the plugin to determine whether a device is the homekit model version then it would theoretically be possible for such an option to hide them.
But i don’t think there is!

**Comment by ShaunRoberts543** [comment]
Different conversation, but since we are communicating.  I am getting this error a lot on my log for all my Meross devices.  Any thoughts?

[17/08/2021, 10:55:05] [Meross] [Foyer] failed to request status as Timeout at new module.exports.TimeoutError (/usr/local/lib/node_modules/homebridge-meross/node_modules/promise-timeout/index.js:44:16).

Thank you,
Shaun

**Comment by bwp91** [comment]
Which version of the plugin are you running?

Which device models do you have? Are you getting this message for literally all your devices? Or limited to specific models you have?

Do these devices work if you try to control them through HomeKit?

Also, do you have your meross username and password configured in the plugin? Or the user key? And these devices are linked to the meross account you have configured (via username+password or userkey) and not a separate meross account?

**Comment by ShaunRoberts543** [comment]
I have the latest 6.7.2, but it has done for the last 2 updates.  It eventually comes around, but this pops up from time to time.  I have almost all switches the 510 and the 550 and yes it does it with all.  I use the cloud login with user name and password.

**Comment by bwp91** [comment]
If it's working sometimes and not other times, I would imagine it's just due to an intermittent connection problem between your homebridge instance and your devices.

The plugin is polling each of your devices every 5 seconds (unless configured differently), it's inevitable that there are going to be moments when perhaps wifi is down.

The plugin is simply logging the (error) result of the polling, it's nothing really to worry about since the polling will continue anyway whether one 'round' is successful or not.

I will change the timeout error to only show when debug is enabled, this will lessen the logging (only for polling, not controlling). If a poll fails then there will still be a message in the log saying `[device] has been reported [offline]`, and subsequently a `reported [online]` when the polling is working again.

**Comment by SemoTech** [comment]
Having these issues as well with latest v6.7.2 Meross plugin

 - One device seems to be unsupported:

> [17/08/2021, 21:47:52] [Meross] [Smart LED Light Strip] is currently not supported, do create a github issue https://git.io/JtfVC

 - The others are HomeKit native and send errors like this:

> [17/08/2021, 21:47:55] [Meross] [Left Garage Smart Plug Mini] failed to request status as Timeout at new module.exports.TimeoutError (/usr/local/lib/node_modules/homebridge-meross/node_modules/promise-timeout/index.js:44:16).
> [17/08/2021, 21:47:57] [Meross] [Smart Plug Mini - Zapper] failed to request status as Timeout at new module.exports.TimeoutError (/usr/local/lib/node_modules/homebridge-meross/node_modules/promise-timeout/index.js:44:16).
> [17/08/2021, 21:47:57] [Meross] [Garage Valve Smart Plug Mini] failed to request status as Timeout at new module.exports.TimeoutError (/usr/local/lib/node_modules/homebridge-meross/node_modules/promise-timeout/index.js:44:16).
> ...etc...

**It seems all HomeKit native devices show "hardware version" 4.0.0 in the Meross App, while non-homekit are v3.0.0** 

Is there really no way to tell the difference in the code, and can't the "hardware version" be read?

**Comment by bwp91** [comment]
Hi @SemoTech 

> One device seems to be unsupported:

Which model is this? 

> The others are HomeKit native and send errors like this:

Do you get this for *all* your devices? Or just specific models?

> It seems all HomeKit native devices show "hardware version" 4.0.0 in the Meross App, while non-homekit are v3.0.0

I don't have a meross homekit native device so can't confirm this. But I do have a device with hardware version 2.0.0, which doesn't technically follow your rule. Would you be confident that this is the distinguishing feature between homekit native and not? For *all* meross models?

> Is there really no way to tell the difference in the code, and can't the "hardware version" be read?

The hardware version can be read by the plugin, but since I didn't know about the hardware difference above, then I didn't know that the plugin could potentially differentiate between homekit-native and not models.

**Comment by bwp91** [comment]
With v6.7.3-beta.2 I have added an option to try out:

<img width="617" alt="Screenshot 2021-08-18 at 13 00 22" src="https://user-images.githubusercontent.com/43026681/129894586-6401fefb-043d-4c18-bc39-a82614781765.png">

The logic for the plugin determining a homekit-native model is solely based on whether the first character of the hardware version is `4`.

It would be nice to get some confirmation from users whether this condition is a definitive rule, in that:

* *any* homekit-native model has this hardware version starting with `4`
* but also *any* non-homekit-native model **doesn't** have a hardware version starting with `4`

**Comment by SemoTech** [comment]
That is outstanding and fast @bwp91 Thank you.   I am glad you also noticed the 4.x.x HomeKit native hardware version.
 
I am also happy to test, but not sure I know how to instal the beta version and how to switch back to the release version...

**Comment by bwp91** [comment]
> That is outstanding and fast @bwp91 Thank you. I am glad you also noticed the 4.x.x HomeKit native hardware version.

I haven’t noticed this myself. I am totally going by what you said earlier!

> I am also happy to test, but not sure I know how to instal the beta version and how to switch back to the release version...

Depends on how you run homebridge -

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

**Comment by SemoTech** [comment]
Sounds good @bwp91 I will try the v6.7.3-beta.2 now.

And yes, seems ALL HomeKit native hardware is v4.0.0 while non-HomeKit is v3.0.0  I have about 10 devices of each kind and they all follow this rule.  

Lastly, you asked which device was unsupported.  It is the Native HomeKit "Smart LED Light Strip" codename "msl320c"

Log for it reads:
`[17/08/2021, 21:47:52] [Meross] [Smart LED Light Strip] is currently not supported, do create a github issue https://git.io/JtfVC`

**Comment by SemoTech** [comment]
@bwp91 I just tried the latest beta, and it seems to work well, except for one HomeKit native device still being "loaded", even tho it's hardware version is confirmed to be v4.0.0

```
[18/08/2021, 06:18:53] [Meross] [Smart Air Purifier] is currently not supported, do create a github issue https://git.io/JtfVC with info:
{"uuid":"21124132413448e1e97270fb","onlineStatus":1,"devName":"Smart Air Purifier","devIconId":"device_map100_un","bindTime":1627763324523494,"deviceType":"map100","subType":"un","channels":[{}],"region":"us","fmwareVersion":"7.2.21","hdwareVersion":"7.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"7.2.21","hbDeviceId":"21066234125427270fb","model":"MAP100"}
```

Note:  I have edited the values so they are not real...

**Comment by bwp91** [comment]
> @bwp91 I just tried the latest beta, and it seems to work well, except for one HomeKit native device still being "loaded":
> 
> ```
> [18/08/2021, 06:18:53] [Meross] [Smart Air Purifier] is currently not supported, do create a github issue https://git.io/JtfVC with info:
> {"uuid":"21124132413448e1e97270fb","onlineStatus":1,"devName":"Smart Air Purifier","devIconId":"device_map100_un","bindTime":1627763324523494,"deviceType":"map100","subType":"un","channels":[{}],"region":"us","fmwareVersion":"7.2.21","hdwareVersion":"7.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"7.2.21","hbDeviceId":"21066234125427270fb","model":"MAP100"}
> ```

Yes this has a hardware version of 7.0.0

**Comment by SemoTech** [comment]
> Yes this has a hardware version of 7.0.0

Shows v4.0.0 for me...
![IMG_17ECC89BF044-1](https://user-images.githubusercontent.com/1452100/129907338-4b8f0117-152f-4867-8a7a-e623c06cc3e8.jpeg)

**Comment by bwp91** [comment]
> > Yes this has a hardware version of 7.0.0
> 
> Shows v4.0.0 for me...
> ![IMG_17ECC89BF044-1](https://user-images.githubusercontent.com/1452100/129907338-4b8f0117-152f-4867-8a7a-e623c06cc3e8.jpeg)
> 
> Except it is unplugged right now so WiFi is n/a

I was referring to the air purifier which you mentioned was hk native, still being loaded, this has a hardware version of 7.0.0

**Comment by SemoTech** [comment]
My bad @bwp91 you are correct, I was looking at the LED Strip... The v7.0.0 must be since the Air Purifier is a different class of device.  
Guess we can add v7.x.x along with V4.0.0 to the whitelist of HomeKit native devices....

Maybe add separate exclusion selectors checkboxes, currently for both V4.0.0 and v7.0.0 and maybe others in the future as they come out, so people can choose which version to exclude...

**Comment by bwp91** [comment]
@SemoTech new beta version 6.7.3-beta.3 should:

* hide the air purifier since now checks for 4 and 7 in the hardware version
* show the MSL320C as a supported device

**Comment by SemoTech** [comment]
> @SemoTech new beta version 6.7.3-beta.3 should:
> 
> * hide the air purifier since now checks for 4 and 7 in the hardware version
> * show the MSL320C as a supported device

**Confirmed working as expected in latest beta @bwp91 Thank you for the quick fix!**

Question:  What do you mean by "showing the MSL320C as supported device"? Is the LED strip not a v4.0.0 HomeKit native device, and as such should it not just be ignored altogether by the plugin along with all others that are native?

**Comment by bwp91** [comment]
Well in your case it won’t show in fact due to the “ignore native devices” being ticked. But if this wasn’t ticked then you’d find the accessory would appear in homekit. Before it wouldn’t have done!

I was being very general with my bullet points 😆

**Comment by SemoTech** [comment]
> Well in your case it won’t show in fact due to the “ignore native devices” being ticked. But if this wasn’t ticked then you’d find the accessory would appear in homekit. Before it wouldn’t have done!
> 
> I was being very general with my bullet points 😆

Gotcha, but since the LED strip is a Native HomeKit device it would appear in HomeKit anyway.... 
Any native HK device should be bypassed by this plugin by design, no?

**Comment by bwp91** [comment]
> Gotcha, but since the LED strip is a Native HomeKit device it would appear in HomeKit anyway....

Yes, I meant the accessory that the plugin would create for this device.

> Any native HK device should be bypassed by this plugin by design, no?

I don't believe so. I think it's better to have the choice.

I've added some features to different device types that may not be possible with the native homekit version (like adaptive lighting for lights, Eve history graphs for outlets, switches, power wattage, extra Eve data for garage door openers, etc).

Also I'm not sure if it's so much the case with meross, but I compare to wemo plugin and many users found the homebridge plugin a lot more stable than the wemo native-homekit support, so they use the plugin instead.

Some users may also prefer to have *all* their accessories showing in the Homebridge UI or in HOOBS, but native-homekit accessories would not appear here.

**Comment by SemoTech** [comment]
I agree about having the choice @bwp91 but not sure how HomeKit itself would react if a native device is also "cloned" by your plugin, so two instances are presented to HK...

**Comment by bwp91** [comment]
This wouldn't cause any issues at all. There would simply be two different homekit accessories that control the same physical device. Obviously this is unnecessary.

But anyone has the choice of deleting the homekit native version and using the plugin version, or

Configuring to ignore the plugin version and use the native homekit version.

**Comment by SemoTech** [comment]
Gotcha, good to know they wont butt heads.
Thanks again for the quick implementation.  

I assume that once a new full release is out I'll get notified in the UI to updated even tho I am currently using the beta version?

**Comment by bwp91** [comment]
> I assume that once a new full release is out I'll get notified in the UI to updated even tho I am currently using the beta version?

Yes, stay on the beta, once a proper update is out it will appear as update available in the ui

**Comment by SemoTech** [comment]
Perfect, thank you again @bwp91

**Comment by bwp91** [comment]
@SemoTech 

could you provide me with an exact list of models for which the hardware version is 4 for homekit native version? 

It would make me feel better doing a per-model check as could be for example another model has a non homekit native hardware version of 4 and a homekit native version of 5. In this case obviously with the new option selected, it will hide incorrect accessories 

Also, if you have some free time one day and are happy to assist, I would be interested in implementing the MAP100 device for any user that doesn't have a homekit native model. If such model exists...!

**Comment by SemoTech** [comment]
Hi @bwp91, happy to help and give something back.  

Currently my Pi/Homebridge is not able to route devices to HomeKit, following the v1.10 firmware update of my UDM-Pro from Ubiquiti.  So while I can communicate with the Pi, it is not passing device info to HomeKit and I have not been able to fix it yet, even with support from Reddit members and Ubiquiti's own tier 3 engineers. Here is [my post on Reddit](https://www.reddit.com/r/Ubiquiti/comments/ovhdto/bug_udmpro_lost_proper_vlan_routing_after_v110/) about it...

Now, I do not believe there is such a thing as a non-HomeKit version of the MAP100 Air Purifier since I have not seen it.  If they release one they may change the model designation. For a review of the MAP100, if interested, see mine [HERE.](https://news.semotech.com/product-reviews/meross-homekit-smart-air-purifier/)

As for your request, here are all the Meross unique models I have that are HomeKit Native:
Name:  Smart Bulb     |   Model:   msl120d    |   HW: v4.0.0
Name:  Garage Opener    |   Model:  msg100     |   HW: v4.0.0
Name:  Single Pole Smart Switch    |   Model:  mss510x   |   HW: v4.0.0
Name:  Smart LED Strip    |   Model:  msl320c   |   HW: v4.0.0
Name:  Smart Plug Mini    |   Model:   mss110r    |   HW: v4.0.0
Name:  Smart Air Purifier     |   Model:  MAP100     |   HW: v7.0.0

These are my non-HomeKit devices that Homebridge is managing with your plugin:
Name:  Single Pole Smart Switch    |   Model:  mss510x   |   HW: v3.0.0
Name:  3-Way Smart Switch    |   Model:  mss550x   |   HW: v3.0.0

Do note that the "mss510x" model [single pole smart switch] comes in either HW 3 or 4 so can be either non-HomeKit or HomeKit... I do not have a HomeKit "mss550x" but there could be a HomeKit version out there as well...

Hope this is of some help to you Ben.
