### ISSUE TITLE
MRS100 gets blocked due to much accesses

### ISSUE THREAD

**Issue by rgoggy** [donavanbecker/homebridge-meross#330]
### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

1

* Which version of Homebridge/HOOBS do you have?
1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi docker

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
6.7.0

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
MRS100 all other a blacklisted due to HomeKit available

### Please paste any relevant logs below.

```

```
Mail from Meross that device is blocked due to too much requests

**Comment by bwp91** [comment]
Hi @rgoggy 

Thanks for this. There was an issue with polling for this device where the plugin was requesting status much quicker than planned. This has been fixed in v6.7.2.

You'll probably need to send a very nice email to meross asking them to unblock again (after updating plugin). Maybe explain there was an issue with the homebridge plugin which has been fixed. They'll probably say that homebridge isn't officially supported by Meross, but if you highlight that the issue has been fixed then they should unblock your device(s).

I apologise for this
