### ISSUE TITLE
Eve contact characteristics instead of door

### ISSUE THREAD

**Issue by EIBHomeControl** [donavanbecker/homebridge-meross#371]
I've been using the plugin for scwhile. So far, is working fine.
I have also a nuki smart lock.
I'm using the plugin https://github.com/ebaauw/homebridge-nb#readme

See the screenshot below.

Can you change the characteristics, if possible to choose via config, to the eve contact sensor characteristics?

Best regards
Frank

* **Any particular Meross devices that this relates to?**

Garagedoor opener

* **Anything else?**

Current
![image](https://user-images.githubusercontent.com/5344610/143181777-2fa34b22-30be-4fe1-904c-a69f6cfd67aa.jpeg)

Contact sensor from the nuki smart lock.
As u can see i shows only the opening times. 

![image](https://user-images.githubusercontent.com/5344610/143181818-7e845f75-d893-4d05-9540-b5ba815882c0.jpeg)
![image](https://user-images.githubusercontent.com/5344610/143181834-9aa2863f-9f33-4e13-8e8e-bbb82e87d508.jpeg)

**Comment by bwp91** [comment]
Hi @EIBHomeControl 

Yes as have noticed, the Eve app displays the historical data for the `GarageDoorOpener` and a `ContactSensor` services in a different way, the `ContactSensor` way being nicer to look at.

In all my plugins I used to add an additional `ContactSensor` service to the garage door accessory, so that the data could be seen in both ways.

However what was happening then was that whenever the garage door opened and closed, it was creating double notifications in the home app as effectively the garage door service opened **and** the contact sensor opened (or closed in the same way).

> Can you change the characteristics, if possible to choose via config, to the eve contact sensor characteristics?

It's the same characteristics for both the garage door service and the contact sensor service. The difference is how the Eve app displays this data depending on the service type.
