### ISSUE TITLE
Hi! Please add device Meross msxh0.

### ISSUE THREAD

**Issue by mrfidotkormchiy** [donavanbecker/homebridge-meross#372]
* **Please explain your feature request in a one or two sentences.**

* **Is your feature request related to a problem? Please describe.**

* **Any particular Meross devices that this relates to?**

* **Anything else?**

**Comment by bwp91** [comment]
Hi @mrfidotkormchiy 

Since this is the first humidifier device type that the plugin would support, it would be really handy to be able to message you on discord so I can get more info about this device and the data structures.

Could you join the homebridge discord server and then let me know your username on there to dm you?

https://discord.gg/bHjKNkN

Thanks!

**Comment by mrfidotkormchiy** [comment]
Hi! My name Dmitry _Kh.

Отправлено с iPhone

**Comment by bwp91** [comment]
i’ve tried a couple of times to find you in the online list, but can’t see you.

Next time your on there, can you find me in the list and send me a direct message? i’ll be in the “plugin developers” list and my username is bwp91
