### ISSUE TITLE
Some devices (they're all light switches) stuck in "updating" state

### ISSUE THREAD

**Issue by Conanap** [donavanbecker/homebridge-meross#378]
### What issue do you have? Please be as thorough and explicit as possible.
In the home app, some of these light switches are stuck as "updating" state; these light switches do not originally support homekit.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
- Homebridge UI-X, originally on a beta branch. Issue presented itself so I updated to the latest release (v7.3.1), issue persists.
- JSON setup (with sensitive info removed):
```
{
    "name": "Meross",
    "username": "redacted",
    "password": "redacted",
    "userkey": "redacted",
    "ignoreHKNative": true,
    "debug": true,
    "platform": "Meross"
}
```

* Which version of Homebridge/HOOBS do you have?
homebridge 1.3.8, node.js 14.18.0, npm 6.14.15

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Ran with the docker image via Hyper-V on Windows 10

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
Issue started presenting itself, without any change to plugins and set up, on v7.0.0-beta.10. Updated to v7.3.1, issue persists.

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
mss550x (multiple of these); included logs are for one of these switches named "base stair light".

### Please paste any relevant logs below.
```
[12/9/2021, 5:24:26 PM] [Meross] [Base Stair Light] not initialising cloud device as matched as HomeKit native model.
```

No further logs.

**Comment by bwp91** [comment]
Hi @Conanap 

Is there a reason why you have `ignoreHKNative` set to true? Do you have other native homekit devices you are trying to hide?

It has been reported to me that the mss550x with hardware version 4.0.0 are homekit native, this is the reason that they are not being initialised into your homebridge. In fact, they should not be appearing in your home app at all, rather than being stuck on 'updating' state.

These devices will appear again if you set `ignoreHKNative` to false.

Please let me know if your mss550x models are hardware version 4.0.0 but definitely aren't homekit native.

**Comment by Conanap** [comment]
Hello! Thanks for getting back to me. I do indeed have mixed versions of the mss550x - some support homekit natively, others don't. You are right though, that one does have homekit support so it actualyl ended up being a homekit issue. Sorry for the trouble and thanks for the help!
