### ISSUE TITLE
Add MTS150 to the native Homekit list

### ISSUE THREAD

**Issue by Harti33** [donavanbecker/homebridge-meross#398]
* **Please explain your feature request in a one or two sentences.**
Can you please add the MTS150 to the native Homekit list.

* **Is your feature request related to a problem? Please describe.**
No

* **Any particular Meross devices that this relates to?**
MTS150

* **Anything else?**
Thank you!

**Comment by bwp91** [comment]
Hi @Harti33 

For most devices, the plugin uses the hardware version to determine whether it is the homekit native version or not of a particular model. However for subdevices of the sensor hub (MSH300) the plugin does not have access to this hardware version.

I am hesitant to add this MTS150 to the list since there are both homekit and non-homekit versions available, the plugin cannot tell the difference.

This has reminded me of a feature that I planned to implement when I added support for the MTS devices, the ability to hide a specific sub device from homebridge (at the moment it’s only possible to hide the MSH300 and thus all it’s subdevices).

Using this you would then be able to hide specific radiator thermostats for example if you had a range of homekit and non-homekit models.

**Comment by bwp91** [comment]
If you want to update to the beta version of the plugin, this should allow you to hide and ignore any particular subdevice of a sensor hub, using the subdevice id which now should be logged on plugin startup, you can use the config to enter subdevice ids to ignore.

**Comment by Harti33** [comment]
Thank You. I will try that.

**Comment by bwp91** [comment]
You will need to create an entry in the "Sensor Devices" section of the config screen, with a label, the 32 character ID of the main hub, and then an option will appear below to ignore subdevices. You can enter the subdevice ID in there, and multiple subdevice IDs separated with a comma.

I can't test this myself so please let me know if it works or if you need anything else explained!

**Comment by Harti33** [comment]
Thanks for the quick answer. Unfortunately i can not figure out how to obtain the UUID. Can you help me there?

**Comment by Harti33** [comment]
Nevermind... I found it. 
Works well.
Thank You

**Comment by bwp91** [comment]
Ah great, you’re able to ignore individual subdevices from the hub? Or did you ignore the whole hub?

**Comment by Harti33** [comment]
I just ignore the subdevices that are native to Homekit. The Sensors that are not native still show up as they should. So it works well.

**Comment by bwp91** [comment]
Awesome. Just released v7.7.0 which should (soon) show as an update in your homebridge UI.

Thanks!
