### ISSUE TITLE
Unsupported device

### ISSUE THREAD

**Issue by bobbergen** [donavanbecker/homebridge-meross#534]
[Meross] [Guest Room Ceiling Fan] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2306218954116668080148e1e9caad06","onlineStatus":1,"devName":"Guest Room Ceiling Fan","devIconId":"device_mfc100_us","bindTime":1691609019,"deviceType":"mfc100","subType":"us","channels":[{},{"type":"Light","devName":"light","devIconId":"device_mfc100_us"},{"type":"Fan","devName":"fan","devIconId":"device_mfc100_us"}],"region":"us","fmwareVersion":"7.3.13","hdwareVersion":"7.0.0","userDevIcon":"","iconType":0,"domain":"mqtt-us-2.meross.com","reservedDomain":"mqtt-us-2.meross.com","cluster":2,"hardwareCapabilities":[],"firmware":"7.3.13","hbDeviceId":"2306218954116668080148e1e9caad06","model":"MFC100"}

**Comment by bwp91** [comment]
Hi @bobbergen 

Please update to the beta version of the plugin:

https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

Since this is a brand new device type (never had a fan controller before) it won't start working immediately, but you should notice some logging in the homebridge log whenever you use the meross app to control the device.

This is the kind of info I'll need to start implementing the controls properly.

Happy to message on discord if you are on there?
https://discord.gg/kqNCe2D

**Comment by bwp91** [comment]
Closing - update released ignoring this device as seems homekit native :)
